GET  http://localhost:3001/users HTTP/1.1
###
GET  http://localhost:3001/users?token=12345 HTTP/1.1
###
GET  http://localhost:3001/users/5 HTTP/1.1
###
GET  http://localhost:3001/users/5?token=12345 HTTP/1.1
###
POST   http://localhost:3001/users HTTP/1.1
###
POST   http://localhost:3001/users?token=12345 HTTP/1.1

###
PUT    http://localhost:3001/users/5 HTTP/1.1
###
PUT    http://localhost:3001/users/5?token=12345 HTTP/1.1
###
DELETE  http://localhost:3001/users/12 HTTP/1.1
###
DELETE  http://localhost:3001/users/12?token=12345 HTTP/1.1
